name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Weekly build
    - cron:  '10 3 * * 6'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ubuntubase/ubuntubase:$(date +%Y%m%d) --tag ubuntubase/ubuntubase:20.04 --tag ubuntubase/ubuntubase:latest
    - name: Push the Docker image (1)
      run: docker push ubuntubase/ubuntubase:$(date +%Y%m%d)
    - name: Push the Docker image (2)
      run: docker push ubuntubase/ubuntubase:20.04
    - name: Push the docker image (3)
      run: docker push ubuntubase/ubuntubase:latest
