name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Weekly build
    - cron:  '10 3 * * 6'
  workflow_dispatch:

jobs:
  docker:
    strategy:
      matrix:
        version: ["20.04", "22.04", "22.10"]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    # Add support for more platforms with QEMU (optional)
    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        # install: true
        platforms: linux/amd64,linux/arm64

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    # https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
    - name: Set TODAY to current date
      run: echo "TODAY=$(date +'%Y%m%d')" >> $GITHUB_ENV

    - name: Build and push images
      uses: docker/build-push-action@v3
      with:
        context: .
        build-args: "VERSION=${{ matrix.version }}"
        # Supported architectures base image: amd64, arm32v7, arm64v8, i386, ppc64le, riscv64, s390x (source: https://hub.docker.com/_/ubuntu)
        # List of valid platform identifiers: https://www.winters.nz/docker/cross-platform-github-actions/
        platforms: linux/amd64,linux/arm/v7,linux/arm64,linux/386,linux/ppc64le,linux/riscv64,linux/s390x
        tags: ubuntubase/ubuntubase:${{ matrix.version }}-${{env.TODAY}},ubuntubase/ubuntubase:${{ matrix.version }},ubuntubase/ubuntubase:${{ matrix.version }}-latest
        push: true
