name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Weekly build
    - cron:  '10 3 * * 6'

jobs:
  build:
    strategy:
      matrix:
        version: [20.04, 22.04]

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg VERSION=${{ matrix.version }} --tag ubuntubase/ubuntubase:${{ matrix.version }}-$(date +%Y%m%d) --tag ubuntubase/ubuntubase:${{ matrix.version }} --tag ubuntubase/ubuntubase:${{ matrix.version }}-latest
    - name: Push the Docker image (1)
      run: docker push ubuntubase/ubuntubase:${{ matrix.version }}-$(date +%Y%m%d)
    - name: Push the Docker image (2)
      run: docker push ubuntubase/ubuntubase:${{ matrix.version }}
    - name: Push the docker image (3)
      run: docker push ubuntubase/ubuntubase:${{ matrix.version }}-latest
